// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR1pLxN5L2sWKyKMegO_K2SxEJZb_lqoQ',
    appId: '1:120544144848:web:dff287f14c9bfcef075dd5',
    messagingSenderId: '120544144848',
    projectId: 'safeguardsg-7556a',
    authDomain: 'safeguardsg-7556a.firebaseapp.com',
    storageBucket: 'safeguardsg-7556a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXv18MPl15zRDeNbyKk1Wkl6rJ6mwBmw',
    appId: '1:120544144848:android:f8c51ac3ddbba93f075dd5',
    messagingSenderId: '120544144848',
    projectId: 'safeguardsg-7556a',
    storageBucket: 'safeguardsg-7556a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalzZ2pouN9eDCKyagd9VcMJeG0cKfB7M',
    appId: '1:120544144848:ios:e170034a86c5dffa075dd5',
    messagingSenderId: '120544144848',
    projectId: 'safeguardsg-7556a',
    storageBucket: 'safeguardsg-7556a.firebasestorage.app',
    iosBundleId: 'com.example.safeGuardSg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBalzZ2pouN9eDCKyagd9VcMJeG0cKfB7M',
    appId: '1:120544144848:ios:e170034a86c5dffa075dd5',
    messagingSenderId: '120544144848',
    projectId: 'safeguardsg-7556a',
    storageBucket: 'safeguardsg-7556a.firebasestorage.app',
    iosBundleId: 'com.example.safeGuardSg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR1pLxN5L2sWKyKMegO_K2SxEJZb_lqoQ',
    appId: '1:120544144848:web:9ba5cc6d1a895590075dd5',
    messagingSenderId: '120544144848',
    projectId: 'safeguardsg-7556a',
    authDomain: 'safeguardsg-7556a.firebaseapp.com',
    storageBucket: 'safeguardsg-7556a.firebasestorage.app',
  );
}
